### ISSUE TITLE
Module mysql-connection-manager is deprecated

### ISSUE THREAD

**Issue by ledgku** [soomtong/blititor#23]
mysql-connection-managers는 deprecated된 모듈입니다.
모듈을 만든  chill117은 node-mysql 모듈로 변환을 권장하고 있습니다.
(https://github.com/chill117/mysql-connection-manager)

평소 node.js에는 아래 mysql 모듈이 많은 contributer와 star를 얻고 있는 모듈이기에 신뢰성이 높아 많이 사용하고 있습니다.
node-mysql(https://github.com/mysqljs/mysql)

mysql 모듈을 변경하는 것에 대해 의견을 여쭤보고 싶습니다.

**Comment by soomtong** [comment]
어이쿠 며칠 전 디프리케이트 되었군요. 별도의 커넥션 매니저를 준비하던가 mysql 의 커넥션 풀을 직접 사용하도록 해야겠네요.

**Comment by ledgku** [comment]
네^^ node-mysql(https://github.com/mysqljs/mysql)모듈의 커넥션 풀은 사용하기 간단해서 개인적으로 항상 사용하고 있는데요. 멘토님께서 mysql-connection-manager를 사용하신 이유가 궁금하기도 하고 변경 작업을 맡아서 하고도 싶습니다.

혹시 월요일에 멘토님 찾아뵙고 말씀나눠도 될까요?

**Comment by soomtong** [comment]
@ledgku 네 좋아요!

**Comment by ledgku** [comment]
@soomtong 네 감사합니다. 연락드리겠습니다.
