### ISSUE TITLE
bind custom domain

### ISSUE THREAD

**Issue by soomtong** [soomtong/blititor#25]
bind custom domain for `soomtong.github.io/blititor` to `blititor.com`.
it can conflict with other subdomain, maybe, need to find out something...
- blititor.com : github service page, it produced by github's feature.
- plain.blititor.com : demo site, working now.

**Comment by ledgku** [comment]
How about the following sub domain config of Nginx?

server {
        listen       80;
        server_name  localhost;

```
    location / {
        root   /home/nginx;
        index  index.html index.htm;
    }
}

server {
    listen       80;
    server_name  nginx1.appsroot.com;

    location / {
        root   /home/nginx1;
        index  index.html index.htm;
    }
}

server {
    listen       80;
    server_name  nginx2.appsroot.com;

    location / {
        root   /home/nginx2;
        index  index.html index.htm;
    }
}
```

Reference : http://sarc.io/index.php/nginx/61-nginx-nginx-conf

**Comment by soomtong** [comment]
no, i think this is not nginx problems.
refer this. https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

if i m wrong, let me know :)

**Comment by soomtong** [comment]
@ledgku and come `gitter` occasionally, check prev. messages.

**Comment by soomtong** [comment]
현재 도메인 사업자가 루트 도메인에 대해 cname 을 조작하는 방법을 제공하지 않아
이 내용은 드랍합니다.
