### ISSUE TITLE
Mac에서 필수모듈 bcrypt 설치 오류 문제

### ISSUE THREAD

**Issue by parkjunyoung** [soomtong/blititor#28]
맥 os에서

`npm install bcrypt` fails in install: `node-gyp rebuild
라는 메시지가 뜸

원인 : macOS에서 Cli 를 사용할수가 없어서 생기는 문제
해결법 : xcode 설치

혹시 그러고도 에러가 발생시
node-gyp 를 global 로 설치한다.

**Comment by soomtong** [comment]
@parkjunyoung 윈도우즈에서도 같은 문제가 있습니다.

**Comment by parkjunyoung** [comment]
@soomtong  윈도우는 오류 메시지를 보니 python 개발환경이 필요하다고 합니다. 파이썬 설치후 진행해보면 될것같습니다.

**Comment by soomtong** [comment]
#29
