### ISSUE TITLE
Windows10 에서 패키지 설치 문제

### ISSUE THREAD

**Issue by 0122hey** [soomtong/blititor#29]
## 오류 명령어

  `npm i bcrypt`
## 오류 메세지

![image](https://cloud.githubusercontent.com/assets/22411458/18813744/e03bf890-833f-11e6-825d-d78f0b3a6e6f.png)
## 문제 이전
- npm update: 2.49->3.x
  
  `npm -g i npm`

windows10에서도 설치되도록 해결해주세요!

**Comment by soomtong** [comment]
https://futurestud.io/tutorials/how-to-build-nodegyp-to-run-bcrypt-on-windows

**Comment by soomtong** [comment]
> I gave up, just install bcrypt-nodejs :)

https://github.com/ncb000gt/node.bcrypt.js/issues/340#issuecomment-226976412

**Comment by soomtong** [comment]
@0122hey 이렇게 해 보세요

아까 연습했던 과정 생각해 보면서.

`npm i` 하기 전에 파일 하나를 수정하는 겁니다.

`package.json` 파일을 열어서 

```
  "dependencies": {
    "bcrypt": "^0.8.6",
    "body-parser": "^1.13.3",
```

저기에 `bcrypt` 대신 `bcryptjs` 를 쓰는거죠. 물론 파일 버전은 다릅니다.

```
  "dependencies": {
    "bcryptjs": "*",
    "body-parser": "^1.13.3",
```

이렇게 수정하고
`npm i` 가 잘 마무리 되는지 확인 한 후

모든 소스 코드의 

`var bcrypt = require('bcrypt');` 를 `var bcrypt = require('bcryptjs');`로 변경한 후 

나머지 작업을 진행합니다.

완전 힘들겠죠...

**Comment by ghost** [comment]
윈도우10 
`잘됩니다`

**Comment by soomtong** [comment]
패키지 변경 했습니다.
https://github.com/soomtong/blititor/commit/89104b0ccb7f9c63461c0d2bc5818d2c0f99399d

**Comment by soomtong** [comment]
저도 윈도우 10 클린 셋업 상태에서 node, git 만 설치하고 테스트 했습니다.
설치는 이상 없이 잘 되네요.

**Comment by ho1234c** [comment]
os별로 의존성을 다르게 해줘야하나 생각하고있었는데 아예 변경하셨네요. 윈도우7도 잘됩니다.

**Comment by yonghyun123** [comment]
윈도우 7도 잘됩니다.
