### ISSUE TITLE
CLI 셋업시 데이터베이스 설정 시점에 prefix 넣기 항목 추가하기

### ISSUE THREAD

**Issue by soomtong** [soomtong/blititor#30]
`node core/setup.js db`

항목에서 prefix 항목 추가하기

`vi core/config/database_default.json`

디비 세팅(계정 넣고 포트 적고 하는거) 마친후 프리픽스 수정하는거
이거 불편합니다. 그쵸... 

`vi core/config/database_default.json`

구문 참조하세요. 

만족할 결과는 아래의 형태입니다.

CLI 셋업시 

```
soomtong@openlab0 ~/blititor-theme-dev> node core/setup.js db
 = Make database configuration

 B: Enter mysql(maria) host:  localhost
 B: Enter mysql(maria) port:  (3306)
 B: Enter mysql(maria) database name:  (db_blititor)
 B: Enter mysql(maria) user name:  soomtong
 B: Enter your password:  ******
```

이 부분 위에 한 줄 프리픽스 관련 항목을 추가하는 것 그리고 디폴트는

`b_`

만약 사용자가 `b_theme` 를 입력했다면 
또는 `b_theme_` 를,
또는 `theme` 를

```
  1 {
  2     "port": 3306,
  3     "database": "db_blititor",
  4     "prefix": "b_theme_"
  5 }
```

아래의 결과를 만족하면 좋겠습니다.

(수동 테스트 로직이네요;;;)

@ledgku

**Comment by ledgku** [comment]
#39 추가해서 pull request 보냈습니다.^^
