### ISSUE TITLE
Plain theme 에서 로그인, 로그아웃 같이 출력되는 버그

### ISSUE THREAD

**Issue by upgle** [soomtong/blititor#46]
## Problem

Plain theme 에서 사용자 인증 후 login, logout 메뉴 모두 출력되는 문제가 있습니다.
## Screenshot

![image](https://cloud.githubusercontent.com/assets/5635513/18869147/ffba9490-84e5-11e6-9133-5874a472aa9f.png)

**Comment by ho1234c** [comment]
이 문제 수정중입니다.
