### ISSUE TITLE
npm install 설치 시 fatal error:c1060 : 컴파일러 힙 공간이 부족합니다.

### ISSUE THREAD

**Issue by 0122hey** [soomtong/blititor#50]
## 오류 명령어

  `npm install`
## 오류 메세지

![image](https://cloud.githubusercontent.com/assets/22411458/18878577/1f0ef216-850c-11e6-8da3-72f66ff32c04.png)
## 문제 이전
- 리부팅

npm install 중 컴파일러 힙공간이 부족하다고 합니다.
어떻게 해결해야 하는지 도와주세요!

**Comment by soomtong** [comment]
#29
