### ISSUE TITLE
팀블로그에서 새 글 저장이 안되는 오류

### ISSUE THREAD

**Issue by songru** [soomtong/blititor#51]
![batch_undefined_insertid](https://cloud.githubusercontent.com/assets/8120081/18885276/f9f2fdf0-8525-11e6-9cb4-00f1585b9039.jpg)

팀블로그에서 새 글쓰기 후 submit하면 아래와 같은 오류가 발생합니다. 
ypeError: Cannot read property 'insertId' of undefined
    at /Users/hwangcholong/dev/JS/kosslab/blititor/module/teamblog/lib/teamblog.js:170:29

**Comment by soomtong** [comment]
fixed https://github.com/soomtong/blititor/commit/b46e3776333b5106681197b9137772c085e96f02

please restart app after re-pull origin (based repo)
