### ISSUE TITLE
[팀블로그] 가입 후에도 가입버튼이 변경되지 않음

### ISSUE THREAD

**Issue by songru** [soomtong/blititor#52]
![default](https://cloud.githubusercontent.com/assets/8120081/18900254/cc378fb6-857a-11e6-8acc-6cba000368ed.png)

블로그 가입 후 로그인까지 한 상태인데
버튼명이 '팀블로거로 가입하기' 로 나옵니다. 

들어가면 자기 프로필 수정인데, '마이페이지'나 '개인 정보 수정'으로 
변경이 필요할 것 같습니다.

**Comment by soomtong** [comment]
저희가 채택한 html 템플릿 엔진은 https://mozilla.github.io/nunjucks/ 제품인데 아주 좋습니다.
문서 한 번 보시고 직접 수정해보세요. 이건 정말 어렵지 않을거에요.
@ChorongHwang

**Comment by soomtong** [comment]
👍
