### ISSUE TITLE
방명록에서 reply한 것과 아닌 것의 차이가 불분명합니다.

### ISSUE THREAD

**Issue by songru** [soomtong/blititor#53]
![reply_update](https://cloud.githubusercontent.com/assets/8120081/18900553/608cb662-857d-11e6-80ef-a26aef9eccb6.png)

방명록에서 글에 대해 comment를 달면
'reply'버튼만 'update'로 변경되는데, 제대로 저장이 된 것인지 한눈에 파악하기 어렵습니다.

1) reply 전 상태
2) reply 후 상태 (update가능한 상태) 
를 나누어서 표현되어야 할 것 같습니다.

**Comment by soomtong** [comment]
@ChorongHwang 네 완벽히 완성되지 않은 상태로 사용 중입니다. 고쳐 볼 수 있으시면 도전하세요!

**Comment by soomtong** [comment]
f5d647d18ea9361964bf2b192b2cd355b030da5e
단순히 색상 구분으로 사용합니다. (일반적인 패턴은 아니지만 중요한 부분이 아니라고 봅니다)
