### ISSUE TITLE
로고 스타일 투표

### ISSUE THREAD

**Issue by melthleeth** [soomtong/blititor#57]
만들다보니 (정말)미세한 차이가 있는데 가장 마음에 드는 것 한가지만 골라주세요!
## 1. ORIGINAL (5px)

![blititor_logo_round](https://cloud.githubusercontent.com/assets/22411481/18938054/ae149b30-8630-11e6-8055-a3e55d904b68.png)
## 2. ORIGINAL (7px)

![blititor_logo_round7](https://cloud.githubusercontent.com/assets/22411481/18938105/2204422a-8631-11e6-939f-320380d38118.png)
## 3. ORIGINAL (7px + 안의 원 size up)

![blititor_logo_round7bigo](https://cloud.githubusercontent.com/assets/22411481/18938111/285216de-8631-11e6-82a0-aa898309d06f.png)
## 4. reflect NODE.JS icon(7px)

![blititor_logo_nodejsstyle7](https://cloud.githubusercontent.com/assets/22411481/18938134/5bd7305c-8631-11e6-8415-19590e187869.png)
## 5. reflect NODE.JS icon(9px)

![blititor_logo_nodejsstyle9](https://cloud.githubusercontent.com/assets/22411481/18938136/5ddb046e-8631-11e6-813d-7ce44dcbb252.png)

**Comment by songru** [comment]
3번에 투표합니다~

**Comment by upgle** [comment]
2번에 투표합니다~

**Comment by soomtong** [comment]
4

**Comment by ho1234c** [comment]
그렇다면 저는 1번에...

**Comment by ghost** [comment]
4번 좋네용

**Comment by ledgku** [comment]
2번 투표합니다^^

**Comment by parkjunyoung** [comment]
전 4번요

**Comment by greenbag** [comment]
4번이욯ㅎ

**Comment by melthleeth** [comment]
4번으로 채택하였습니다 :)
변경 사항: 육각형 색, 글씨 색, 글자사이 간격 조정

![final2_blititorlogo_t](https://cloud.githubusercontent.com/assets/22411481/18962436/cd87572a-86ab-11e6-8e6b-d145b325e119.png)
