### ISSUE TITLE
크로스브라우징이슈

### ISSUE THREAD

**Issue by ho1234c** [soomtong/blititor#59]
크롬을 제외한 타 브라우저에서 레이아웃및 기능이 깨집니다. 이단계에서 크로스브라우징을 신경쓰는건 욕심일 수도 있지만 (한국형 CMS라면 특히나) 언젠가 해결해야할 문제입니다.
1. Chrome (v. 53.0.2785.116 m)
   ![image](https://cloud.githubusercontent.com/assets/11595293/18938560/65db98e2-8634-11e6-9e32-aa3210e18470.png)
2. Firefox (v. 47.0.1)
   ![image](https://cloud.githubusercontent.com/assets/11595293/18938667/4721c6fa-8635-11e6-8428-d5ab27a726a9.png)
3. IE 8
   ![image](https://cloud.githubusercontent.com/assets/11595293/18938635/01293494-8635-11e6-81b4-3b8214c1ebc9.png)

**Comment by upgle** [comment]
IE8 지원까지는 어렵지 않을까요? 현재 점유율이 5% 미만으로 알고 있습니다.
요즘 하는 프로젝트들은 대부분 IE10-11 정도부터 시작하는것 같더라구요 ^^;

**Comment by ho1234c** [comment]
네. 제 생각에도 8까지는 아닌것같지만.. IE는 분명 지원해야 할거같습니다.

**Comment by ryuneeee** [comment]
ie8은... 놓아줘야한다고 봐요....ㅋㅋㅋ

**Comment by soomtong** [comment]
알파 스테이지(외부 공개되고 베타 테스팅 되는 시점. 언제 올까?)에서 프론트엔드 이슈는 배제해도 좋겠습니다.
